<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, February 22, 2025 2:31:31 PM</msg><msg code="1" type="100">﻿Traceback (most recent call last):
﻿  File "C:\Users\ckb010\bruns-online-GEOG676-spring2025\Labs\lab_5\lab_5_ArcPro\lab5_Toolbox.pyt", line 109, in execute
﻿    spatial_ref = arcpy.Describe(buildings).satialReference
﻿                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
﻿AttributeError: DescribeData: Method satialReference does not exist
</msg><msg code="-2147467259" type="100">Failed to execute (tool).</msg><msg code="0" type="3">Failed at Saturday, February 22, 2025 2:31:35 PM (Elapsed Time: 3.76 seconds)</msg></messages>